package io.softa.starter.flow.runtime.state;

import java.time.LocalDateTime;
import java.util.List;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import io.softa.starter.flow.enums.VoteThresholdMode;

/**
 * Pending approval task generated by the in-memory runtime skeleton.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(name = "PendingApproval")
public class PendingApproval {

    @Schema(description = "FlowBundle.id for this pending approval's flow (primary runtime key)")
    private Long bundleId;

    @Schema(description = "Flow code (display/logging only)")
    private String flowCode;

    @Schema(description = "Resolved published flow revision (display/logging only)")
    private Integer flowRevision;

    @Schema(description = "Node id")
    private String nodeId;

    @Schema(description = "Node label")
    private String nodeLabel;

    @Schema(description = "Approval task cycle number for repeated visits to the same node")
    private Integer cycleNumber;

    @Schema(description = "Static approver ids or names from config")
    private List<String> approvers;

    @Schema(description = "Whether approvers were resolved from a dynamic source")
    private Boolean dynamicApprovers;

    @Schema(description = "Approval mode for this node")
    private VoteThresholdMode approvalMode;

    @Schema(description = "Required approval count before the node can continue")
    private Integer requiredApprovalCount;

    @Schema(description = "Total configured approver count")
    private Integer totalApproverCount;

    @Schema(description = "Reject mode for this node")
    private VoteThresholdMode rejectMode;

    @Schema(description = "Required reject count before the node is rejected")
    private Integer requiredRejectCount;

    @Schema(description = "Approvers who have already approved in unanimous mode")
    private List<String> approvedActors;

    @Schema(description = "Approvers who have already rejected in threshold-based reject mode")
    private List<String> rejectedActors;

    @Schema(description = "Actor who is currently blocked by an unresolved add-sign dependency")
    private String blockedActorId;

    @Schema(description = "Actor who must approve before the blocked actor can proceed")
    private String prerequisiteActorId;

    @Schema(description = "Due time computed from timeout config when the approval was created")
    private LocalDateTime dueTime;

    @Schema(description = "Number of timeout reminders already sent")
    private Integer remindCount;

    @Schema(description = "Timestamp of the last timeout reminder sent")
    private LocalDateTime lastRemindTime;
}

