# syntax=docker/dockerfile:1.7

FROM eclipse-temurin:25-jre-alpine

ARG APP_NAME
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./deploy/entrypoint.sh /app/entrypoint.sh
COPY ./app/${APP_NAME}.jar /app/${APP_NAME}.jar

WORKDIR /app
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
