package io.softa.starter.flow.runtime.bundle;

import io.softa.starter.flow.api.CompiledFlowCapabilitySummary;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import io.softa.starter.flow.design.FlowFormBinding;
import io.softa.starter.flow.design.trigger.TriggerSource;
import io.softa.starter.flow.enums.ApproverDedupStrategy;
import io.softa.starter.flow.enums.FlowScenario;

/**
 * Immutable runtime bundle generated by publish-time compilation.
 * <p>
 * Key changes from the previous model:
 * <ul>
 *   <li>{@code scenario} ({@link FlowScenario}) replaces the former {@code kind}
 *       ({@code FlowKind}) + {@code purpose} ({@code FlowPurpose}) two-dimensional matrix.</li>
 *   <li>{@code trigger} is now a {@link TriggerSource} sealed-interface reference,
 *       replacing the former flat {@code FlowTriggerDefinition}.</li>
 *   <li>{@code declaredOutputs} is a new field listing the variable names that this
 *       flow promises to produce; required for {@link FlowScenario#VALIDATION} and
 *       {@link FlowScenario#COMPUTE} flows.</li>
 * </ul>
 */
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
@Schema(name = "CompiledFlowDefinition")
public class CompiledFlowDefinition {

    @Schema(description = "Flow code")
    private String flowCode;

    @Schema(description = "Flow name")
    private String flowName;

    @Schema(description = "Execution scenario (replaces kind + purpose)")
    private FlowScenario scenario;

    @Schema(description = "Compiled trigger contract (sealed TriggerSource sub-type)")
    private TriggerSource trigger;

    @Schema(description = "Compiled form bindings")
    private List<FlowFormBinding> forms;

    @Schema(description = "Whether the initiator can withdraw the flow before approval completes")
    private Boolean allowInitiatorWithdraw;

    @Schema(description = "Whether the flow executes synchronously within the triggering transaction")
    private Boolean sync;

    @Schema(description = "Whether to roll back the triggering transaction on flow failure (only when sync=true)")
    private Boolean rollbackOnFail;

    @Schema(description = "Approver consolidation policy (审批人去重); null = GLOBAL at runtime")
    private ApproverDedupStrategy approverDedup;

    /**
     * Declared output variable names.
     * <ul>
     *   <li>Required for {@link FlowScenario#VALIDATION} and {@link FlowScenario#COMPUTE}
     *       flows — the caller inspects these keys from {@code FlowExecutionState.outputs}.</li>
     *   <li>Optional for {@link FlowScenario#PROCESS} flows.</li>
     * </ul>
     */
    @Schema(description = "Variable names this flow promises to produce in FlowExecutionState.outputs")
    private List<String> declaredOutputs;

    // ── Graph topology ─────────────────────────────────────────────────────

    @Schema(description = "Entry node ids")
    private List<String> entryNodeIds;

    @Schema(description = "Terminal node ids")
    private List<String> terminalNodeIds;

    /**
     * Topological node order — a compile-time output used to verify the sort (and available to tooling).
     * The runtime engine traverses by edges, so it is neither read at runtime nor persisted in the bundle.
     */
    @JsonIgnore
    @Schema(hidden = true)
    private List<String> topologicalOrder;

    @Schema(description = "Node index")
    private Map<String, CompiledFlowNode> nodeIndex;

    @Schema(description = "Transition index")
    private Map<String, CompiledFlowTransition> transitionIndex;

    @Schema(description = "Derived capability summary")
    private CompiledFlowCapabilitySummary capabilitySummary;

    // ── Revision metadata ──────────────────────────────────────────────────

    @Schema(description = "Published revision number")
    private Integer revision;

    @Schema(description = "Exact FlowBundle.id (primary runtime key; globally unique, no tenant collision)")
    private Long bundleId;

    @Schema(description = "Owning tenant id (stamped from the FlowBundle row; used for match-time tenant isolation; 0 = platform-shared)")
    private Long tenantId;

    @Schema(description = "Source FlowDesign.id (stable flow handle across revisions)")
    private Long designId;

    @Schema(description = "Compiled timestamp")
    private LocalDateTime compiledAt;

    @Schema(description = "Published timestamp")
    private LocalDateTime publishedAt;
}
