package io.softa.starter.studio.template.ddl;

import java.util.Map;
import org.junit.jupiter.api.Test;

import io.softa.framework.orm.enums.FieldType;
import io.softa.starter.studio.template.ddl.context.FieldDdlCtx;
import io.softa.starter.studio.template.ddl.context.IndexDdlCtx;
import io.softa.starter.studio.template.ddl.context.ModelDdlCtx;
import io.softa.starter.studio.template.generator.TemplateEngine;

import static org.junit.jupiter.api.Assertions.assertEquals;

class PebbleSqlTemplateWhitespaceTest {

    @Test
    void mysqlCreateTableKeepsEachColumnOnItsOwnLine() {
        ModelDdlCtx model = baseModel("orders", "Order", "id", true);
        model.getCreatedFields().add(field("id", "BIGINT", "BIGINT", true, true, null, "ID"));
        model.getCreatedFields().add(field("name", "VARCHAR", "VARCHAR(100)", true, false, null, "Name"));

        String sql = render("templates/sql/mysql/CreateTable.peb", model);

        assertEquals("""
                /* Create table for model: Order */
                CREATE TABLE orders (
                    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
                    name VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'Name',
                    PRIMARY KEY (id)
                ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Order';
                """.stripTrailing(), sql.stripTrailing());
    }

    @Test
    void mysqlAlterTableKeepsClauseBoundariesIntact() {
        ModelDdlCtx model = baseModel("orders", "Order", "id", false);
        model.setDescriptionChanged(true);
        model.getCreatedFields().add(field("name", "VARCHAR", "VARCHAR(100)", true, false, null, "Name"));
        model.getDeletedFields().add(field("removed_at", "DATETIME", "DATETIME", false, false, null, "Removed At"));
        model.getUpdatedFields().add(field("amount", "DECIMAL", "DECIMAL(10,2)", true, false, "0", "Amount"));
        model.getRenamedFields().add(renamedField("old_status", "status", "VARCHAR", "VARCHAR(20)", true, false, null, "Status"));

        String sql = render("templates/sql/mysql/AlterTable.peb", model);

        assertEquals("""
                /* Alter table for model: Order */
                ALTER TABLE orders COMMENT 'Order',
                    ADD COLUMN name VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'Name',
                    DROP COLUMN removed_at,
                    MODIFY COLUMN amount DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT 'Amount',
                    CHANGE COLUMN old_status status VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'Status';
                """.stripTrailing(), sql.stripTrailing());
    }

    @Test
    void mysqlAlterIndexSeparatesStatementsWithNewlines() {
        ModelDdlCtx model = baseModel("orders", "Order", "id", false);
        model.getDeletedIndexes().add(index("idx_old", false, "old_col"));
        model.getCreatedIndexes().add(index("idx_name", true, "name"));
        model.getUpdatedIndexes().add(index("idx_amount", false, "amount"));
        model.getRenamedIndexes().add(renamedIndex("old_status_idx", "status_idx", true, false, "status"));
        model.getRenamedIndexes().add(renamedIndex("old_name_idx", "name_idx", false, false, "name"));

        String sql = render("templates/sql/mysql/AlterIndex.peb", model);

        assertEquals("""
                /* Table indexes for model: Order */
                ALTER TABLE orders DROP INDEX idx_old;
                ALTER TABLE orders ADD UNIQUE INDEX idx_name (name);
                ALTER TABLE orders DROP INDEX idx_amount;
                ALTER TABLE orders ADD INDEX idx_amount (amount);
                ALTER TABLE orders DROP INDEX old_status_idx;
                ALTER TABLE orders ADD INDEX status_idx (status);
                ALTER TABLE orders RENAME INDEX old_name_idx TO name_idx;
                """.stripTrailing(), sql.stripTrailing());
    }

    @Test
    void postgresqlCreateTableKeepsPrimaryKeySectionOnSeparateLine() {
        ModelDdlCtx model = baseModel("orders", "Order", "id", false);
        model.getCreatedFields().add(field("id", "BIGINT", "BIGINT", true, true, null, "ID"));
        model.getCreatedFields().add(field("name", "VARCHAR", "VARCHAR(100)", true, false, null, "Name"));

        String sql = render("templates/sql/postgresql/CreateTable.peb", model);

        assertEquals("""
                /* Create table for model: Order */
                CREATE TABLE orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    name VARCHAR(100) NOT NULL DEFAULT '',
                    PRIMARY KEY (id)
                );
                COMMENT ON TABLE orders IS 'Order';
                COMMENT ON COLUMN orders.id IS 'ID';
                COMMENT ON COLUMN orders.name IS 'Name';
                """.stripTrailing(), sql.stripTrailing());
    }

    @Test
    void postgresqlAlterTableKeepsStatementsSeparated() {
        ModelDdlCtx model = baseModel("archived_orders", "Archived Order", "id", false);
        model.setRenamed(true);
        model.setOldTableName("orders");
        model.setDescriptionChanged(true);
        model.getCreatedFields().add(field("status", "VARCHAR", "VARCHAR(20)", true, false, null, "Status"));
        model.getDeletedFields().add(field("removed_at", "TIMESTAMP", "TIMESTAMP", false, false, null, "Removed At"));
        model.getUpdatedFields().add(field("amount", "NUMERIC", "NUMERIC(10,2)", true, false, "0", "Amount"));
        model.getRenamedFields().add(renamedField("old_name", "name", "VARCHAR", "VARCHAR(100)", true, false, null, "Name"));

        String sql = render("templates/sql/postgresql/AlterTable.peb", model);

        assertEquals("""
                /* Alter table for model: Archived Order */
                ALTER TABLE orders RENAME TO archived_orders;
                COMMENT ON TABLE archived_orders IS 'Archived Order';
                ALTER TABLE archived_orders ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT '';
                COMMENT ON COLUMN archived_orders.status IS 'Status';
                ALTER TABLE archived_orders DROP COLUMN removed_at;
                ALTER TABLE archived_orders ALTER COLUMN amount TYPE NUMERIC(10,2);
                ALTER TABLE archived_orders ALTER COLUMN amount SET NOT NULL;
                ALTER TABLE archived_orders ALTER COLUMN amount SET DEFAULT 0;
                COMMENT ON COLUMN archived_orders.amount IS 'Amount';
                ALTER TABLE archived_orders RENAME COLUMN old_name TO name;
                ALTER TABLE archived_orders ALTER COLUMN name TYPE VARCHAR(100);
                ALTER TABLE archived_orders ALTER COLUMN name SET NOT NULL;
                ALTER TABLE archived_orders ALTER COLUMN name SET DEFAULT '';
                COMMENT ON COLUMN archived_orders.name IS 'Name';
                """.stripTrailing(), sql.stripTrailing());
    }

    @Test
    void postgresqlAlterIndexSeparatesStatementsWithNewlines() {
        ModelDdlCtx model = baseModel("orders", "Order", "id", false);
        model.getDeletedIndexes().add(index("idx_old", false, "old_col"));
        model.getCreatedIndexes().add(index("idx_name", true, "name"));
        model.getUpdatedIndexes().add(index("idx_amount", false, "amount"));
        model.getRenamedIndexes().add(renamedIndex("old_status_idx", "status_idx", true, false, "status"));
        model.getRenamedIndexes().add(renamedIndex("old_name_idx", "name_idx", false, false, "name"));

        String sql = render("templates/sql/postgresql/AlterIndex.peb", model);

        assertEquals("""
                /* Table indexes for model: Order */
                DROP INDEX idx_old;
                CREATE UNIQUE INDEX idx_name ON orders (name);
                DROP INDEX idx_amount;
                CREATE INDEX idx_amount ON orders (amount);
                DROP INDEX old_status_idx;
                CREATE INDEX status_idx ON orders (status);
                ALTER INDEX old_name_idx RENAME TO name_idx;
                """.stripTrailing(), sql.stripTrailing());
    }

    private String render(String templatePath, ModelDdlCtx model) {
        return TemplateEngine.render(templatePath, Map.of("model", model));
    }

    private ModelDdlCtx baseModel(String tableName, String description, String pkColumn, boolean autoIncrementPrimaryKey) {
        ModelDdlCtx model = new ModelDdlCtx();
        model.setModelName(tableName);
        model.setLabelName(description);
        model.setTableName(tableName);
        model.setDescription(description);
        model.setPkColumn(pkColumn);
        model.setAutoIncrementPrimaryKey(autoIncrementPrimaryKey);
        return model;
    }

    private FieldDdlCtx field(String columnName,
                              String dbType,
                              String typeDeclaration,
                              boolean required,
                              boolean autoIncrement,
                              String defaultValue,
                              String description) {
        FieldDdlCtx field = new FieldDdlCtx();
        field.setColumnName(columnName);
        field.setDbType(dbType);
        field.setFieldType(FieldType.STRING);
        field.setTypeDeclaration(typeDeclaration);
        field.setRequired(required);
        field.setAutoIncrement(autoIncrement);
        field.setDefaultValue(defaultValue);
        field.setDescription(description);
        return field;
    }

    private FieldDdlCtx renamedField(String oldColumnName,
                                     String columnName,
                                     String dbType,
                                     String typeDeclaration,
                                     boolean required,
                                     boolean autoIncrement,
                                     String defaultValue,
                                     String description) {
        FieldDdlCtx field = field(columnName, dbType, typeDeclaration, required, autoIncrement, defaultValue, description);
        field.setOldColumnName(oldColumnName);
        return field;
    }

    private IndexDdlCtx index(String indexName, boolean unique, String... columns) {
        IndexDdlCtx index = new IndexDdlCtx();
        index.setIndexName(indexName);
        index.setUnique(unique);
        index.setColumns(java.util.List.of(columns));
        return index;
    }

    private IndexDdlCtx renamedIndex(String oldIndexName,
                                     String indexName,
                                     boolean definitionChanged,
                                     boolean unique,
                                     String... columns) {
        IndexDdlCtx index = index(indexName, unique, columns);
        index.setOldIndexName(oldIndexName);
        index.setDefinitionChanged(definitionChanged);
        return index;
    }
}
