services:

  elasticsearch:
    image: elasticsearch:9.3.1
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - ~/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    # The limits and reservations are set at the container level, not the service level.
    deploy:
      resources:
        limits:
          cpus: '1'           # Limit to 1 CPU core
          memory: 1GB            # Limit container to 1GB memory (must be greater than ES_JAVA_OPTS)
        reservations:
          memory: 1GB          # Ensure at least 1GB memory allocation

  kibana:
    image: kibana:9.3.1
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      # Kibana connects to ES address
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    # Container-level resource limits
    deploy:
      resources:
        limits:
          cpus: '1'           # Limit to 0.5 CPU core
          memory: 1GB          # Limit container to 512MB memory (must be greater than ES_JAVA_OPTS)
        reservations:
          memory: 512M