package io.softa.starter.user.controller;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import lombok.RequiredArgsConstructor;
import tools.jackson.databind.JsonNode;

import io.softa.framework.orm.domain.Filters;
import io.softa.framework.web.response.ApiResponse;
import io.softa.starter.user.dto.WizardSaveDTO;
import io.softa.starter.user.entity.Role;
import io.softa.starter.user.entity.RoleNavigation;
import io.softa.starter.user.entity.UserRoleRel;
import io.softa.starter.user.enums.RoleSource;
import io.softa.starter.user.service.DynamicRoleSyncJob;
import io.softa.starter.user.service.RoleNavigationService;
import io.softa.framework.orm.service.ModelService;
import io.softa.starter.user.service.RoleService;
import io.softa.starter.user.service.UserRoleRelService;
import io.softa.starter.user.util.JsonArrayUtils;

/**
 * Admin Wizard role management — only the non-CRUD endpoints. Plain CRUD
 * (list / get / create / update / delete) is auto-generated by EntityController
 * on the Role service. See B.2 in permission-design-v4.md.
 */
@Tag(name = "Admin Role")
@RestController
@RequestMapping("/admin/role")
@RequiredArgsConstructor
public class RoleController {

    private final RoleService roleService;
    private final RoleNavigationService roleNavigationService;
    private final UserRoleRelService userRoleRelService;
    private final DynamicRoleSyncJob dynamicRoleSyncJob;
    /** Used for explicit-null column updates that bypass the entity-based
     *  {@code ignoreNull=true} semantics (e.g. wizard "Clear" on
     *  dynamicFilter). The map-based updateOne writes whatever keys are
     *  present in the map, null values included. */
    private final ModelService<?> modelService;

    @PostMapping("/wizard")
    @Transactional
    @Operation(summary = "Wizard create — insert Role + role_navigation + user_role rows (Manual + Dynamic) in one transaction; returns new role id")
    public ApiResponse<Long> createWithWizard(@RequestBody @Valid WizardSaveDTO body) {
        Role role = parseRole(body.roleUpdate());
        role.setId(null);
        Long newId = roleService.createOne(role);
        writeRoleNavigations(newId, body.roleNavigations());
        writeManualUserRoleRels(newId, body.userIds());
        // Inline DYNAMIC sync — same in-transaction guarantee. The cron
        // job covers the in-between drift (employee data changes between
        // role saves) once it's running.
        dynamicRoleSyncJob.syncRole(role.getTenantId(), newId);
        return ApiResponse.success(newId);
    }

    @PutMapping("/{id}/wizard")
    @Transactional
    @Operation(summary = "Wizard update — refresh Role basics, rewrite role_navigation rows and user_role rows (Manual + Dynamic) in one transaction")
    public ApiResponse<Void> saveWizard(@PathVariable Long id, @RequestBody @Valid WizardSaveDTO body) {
        Role role = parseRole(body.roleUpdate());
        role.setId(id);
        roleService.updateOne(role, true);
        // Wizard "Clear" on the dynamic membership rule sends
        // {"dynamicFilter": null} explicitly. The entity-based updateOne
        // above runs with ignoreNull=true (to avoid clobbering fields the
        // wizard payload didn't touch, e.g. code / tenantId), which means
        // it skips null values — including our intended clear. Issue a
        // targeted column-only update through the framework's map-based
        // ModelService.updateOne, which writes whatever keys are in the
        // map regardless of their value, so the SQL becomes a literal
        // `SET dynamic_filter = NULL`.
        if (isExplicitNull(body.roleUpdate(), "dynamicFilter")) {
            Map<String, Object> clearFields = new HashMap<>();
            clearFields.put("id", id);
            clearFields.put("dynamicFilter", null);
            modelService.updateOne("Role", clearFields);
        }
        roleNavigationService.deleteByFilters(new Filters().eq(RoleNavigation::getRoleId, id));
        writeRoleNavigations(id, body.roleNavigations());
        // Wipe ALL existing user_role rows for this role — both Manual and
        // Dynamic — then rebuild from scratch. By application convention
        // there's at most one row per (user, role): Manual takes precedence,
        // syncRole inserts Dynamic only for users not in the Manual list.
        // Doing a full wipe (instead of delta upsert) keeps the logic
        // trivially correct: no "what about old rows that should be
        // upgraded/downgraded" branches. The whole save is in one
        // @Transactional so external observers never see the empty state.
        userRoleRelService.deleteByFilters(
                new Filters().eq(UserRoleRel::getRoleId, id));
        writeManualUserRoleRels(id, body.userIds());
        dynamicRoleSyncJob.syncRole(role.getTenantId(), id);
        return ApiResponse.success();
    }

    /** True when {@code payload} contains {@code field} as a JSON null
     *  (vs. the field being absent). Used to tell apart "wizard didn't
     *  touch this field" from "wizard explicitly cleared this field" —
     *  the latter needs a column-only update to actually write NULL,
     *  because the entity-based updateOne runs with ignoreNull=true. */
    private static boolean isExplicitNull(JsonNode payload, String field) {
        if (payload == null || !payload.has(field)) return false;
        JsonNode value = payload.get(field);
        return value == null || value.isNull();
    }

    /** Maps the wizard's `roleUpdate` JSON (name / description / active /
     *  dynamicFilter) into a Role entity. We extract each field by hand
     *  instead of going through JsonUtils.jsonNodeToObject(Class<T>) because
     *  the runtime Jackson lacks the `treeToValue(JsonNode, Class)` overload
     *  the helper relies on (NoSuchMethodError on call).
     *
     *  <p>Explicit-null fields (e.g. wizard "Clear" on dynamicFilter) stay
     *  out of the entity here — see {@link #saveWizard} for the targeted
     *  follow-up update that actually writes NULL. */
    private Role parseRole(JsonNode payload) {
        Role role = new Role();
        if (payload == null || payload.isNull()) return role;
        JsonNode name = payload.get("name");
        if (name != null && !name.isNull()) role.setName(name.asString());
        JsonNode description = payload.get("description");
        if (description != null && !description.isNull()) role.setDescription(description.asString());
        JsonNode active = payload.get("active");
        if (active != null && !active.isNull()) role.setActive(active.asBoolean());
        JsonNode dynamicFilter = payload.get("dynamicFilter");
        if (dynamicFilter != null && !dynamicFilter.isNull()) role.setDynamicFilter(dynamicFilter);
        return role;
    }

    /** Inserts one user_role row per id in the wizard payload with source=MANUAL.
     *  Skips when payload is null / not an array / empty. Duplicate ids in the
     *  payload are de-duped (a single (user, role, MANUAL) row is enough).
     *  UserAccount ids arrive as JSON strings (frontend serializes all ids as
     *  string per type convention) but may be numbers in tests — {@link
     *  JsonArrayUtils#toLongList} accepts both. */
    private void writeManualUserRoleRels(Long roleId, JsonNode idsJson) {
        java.util.Set<Long> userIds = new java.util.LinkedHashSet<>(JsonArrayUtils.toLongList(idsJson));
        if (userIds.isEmpty()) return;
        List<UserRoleRel> rows = new ArrayList<>(userIds.size());
        for (Long userId : userIds) {
            UserRoleRel ur = new UserRoleRel();
            ur.setUserId(userId);
            ur.setRoleId(roleId);
            ur.setSource(RoleSource.MANUAL);
            rows.add(ur);
        }
        userRoleRelService.createList(rows);
    }

    /** Writes one role_navigation row per entry in the wizard payload. Incoming
     *  `id` and `roleId` from the frontend are ignored — id is auto-assigned,
     *  roleId is bound from the path / newly-created id by the caller. */
    private void writeRoleNavigations(Long roleId, JsonNode rowsJson) {
        if (rowsJson == null || !rowsJson.isArray() || rowsJson.isEmpty()) return;
        List<RoleNavigation> rows = new ArrayList<>(rowsJson.size());
        for (JsonNode row : rowsJson) {
            RoleNavigation rn = new RoleNavigation();
            rn.setRoleId(roleId);
            JsonNode navIdNode = row.get("navigationId");
            rn.setNavigationId(navIdNode == null || navIdNode.isNull() ? null : navIdNode.asString());
            rn.setPermissionIds(row.get("permissionIds"));
            rn.setDataScopes(row.get("dataScopes"));
            rn.setSensitiveFieldSetIds(row.get("sensitiveFieldSetIds"));
            rows.add(rn);
        }
        roleNavigationService.createList(rows);
    }

}
